# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2017-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

dist: trusty
sudo: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

services:
  - redis-server
  - memcached

env:
  - REQUIREMENTS=lowest CACHE_TYPE=redis
  - REQUIREMENTS=lowest CACHE_TYPE=memcached
  - REQUIREMENTS=release CACHE_TYPE=redis DEPLOY=true
  - REQUIREMENTS=release CACHE_TYPE=memcached
  - REQUIREMENTS=devel CACHE_TYPE=redis
  - REQUIREMENTS=devel CACHE_TYPE=memcached

python:
  - "2.7"
  - "3.5"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e all --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e all --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e all --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: "aCBExgUfZuVTICU9wXKaXfAYqdihYo1AQkabCtgOd1gUipmtzt0vvWg3K6Bl3YwvM5isQxsfN/oYvbYdSObzVV7L98wdwfI9NZggwjDs2eO7XFHODtmlN/KneGcc8kdOjdTXA9G1d/D3WizAxc6uaid+Juk0QWrXgjKQhhwu2XzVcXCrLg6n0cLvi4f5ET0KWbrzaATi6ohmRJuoJphVKKZSFyeDcPLThwF7y5RmPleBCOCCPyEDAFPsCRV8l1ZjnLD5vXrOHOINHCxBrw+ehaJ69zQ91faHhPViQuXQlT+zHi1NUX420cLcSoZGPXuI1Ol5qkRT3rxl+yFhQD9PgNcCux3uh6RUfsUwZHIiBb76Kpn/gZ2pjUG2+xgLRcM4P/sA0qAp4ft3Gmw/DHinfeXl5vtNZPaetnoLVRVHzgKZ15Ks30Rg5RcfIc/LVxGHXS1BSJIwkUx3XCVzazJVl6PKKzpHg2NDNRQ4BHQF2/C3TLDtp0S5LjM8DU6sW6K2lDUqeg8/XWqFFUdfkK3WAc/UfZ6myVvZ0Hw9Lu5FysgBnJFmHrBj09ZOFVuIrksuv+59JArNGP9MW64zYYo/4/xw5dhOMJkKhLJmqaArVlh8AjiOn1trxrid2nIO0m1q5eqlvWdd1uktes89yG/rRI8EBcb3tLk1ZX0c+Q63Wi0="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    repo: inveniosoftware/invenio-cache
    condition: $DEPLOY = true
